spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://scrap-db.c6jykanluvmb.ap-northeast-2.rds.amazonaws.com:3306/SCRAP?useUnicode=true&characterEncoding=utf8&verifyServerCertificate=false&useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: readnumber
    password: readnumber!1
    tomcat:
      max-active: 50

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
chat-chat-practice-0:
  0:
    1-SNAPSHOT:
      jar:
server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web: DEBUG
    com:
      example:
        chat: DEBUG


polygon:
  api:
    key: YOUR_POLYGON_API_KEY
    base-url: https://api.polygon.io

